# ---------------------------------------------------------------------------
# clist_01o10_a_test.py
# Created on: 2012-11-26 13:12:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
tbsm1m_7cir_nw_img = "G:\\ArcGISShare\\Geodatabase\\TBSM_builds\\tbsm1m_7cir_nw.img"
tb150_140m_nw_liz = "G:\\ArcGISShare\\Geodatabase\\TBSM_builds\\carto_contours\\contours_01o10_201211.gdb\\U84_N88m_data\\tb150_140m_nw_liz"

# Process: Contour List
arcpy.gp.ContourList_sa(tbsm1m_7cir_nw_img, tb150_140m_nw_liz, "-150;-149;-148;-147;-146")

